### ISSUE TITLE
fetch failed to get commit...

### ISSUE THREAD

**Issue by Jeffrey-Sarnoff** [helgee/JPLEphemeris.jl#9]
when updating (Pkg.update()) v.0.5-dev

ERROR: Base.Pkg.PkgError("JPLEphemeris: fetch failed to get commit 0de12c06cb, please file an issue at https://github.com/helgee/JPLEphemeris.jl/issues")

**Comment by helgee** [comment]
I could reproduce the problem but have no idea what caused it. Deleting my `.julia/v0.5` and re-downloading the package fixed it though.

**Comment by helgee** [comment]
I am closing this since I am not able to reproduce the problem anymore after nuking my v0.5 directory.
